## Append samples of your project ##
resources:
- operator_v1alpha1_jumpstarter.yaml
- jumpstarter.dev_v1alpha1_client.yaml
- jumpstarter.dev_v1alpha1_exporter.yaml
- jumpstarter.dev_v1alpha1_exporteraccesspolicy.yaml
- jumpstarter.dev_v1alpha1_lease.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
