apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - install-operator.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/part-of: jumpstarter-controller
  app.kubernetes.io/managed-by: microshift

